<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM5qszJh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM5qszJh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM5qszJh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM5qszJh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM5qszJh\App_KernelDevDebugContainer([
    'container.build_hash' => 'M5qszJh',
    'container.build_id' => '6e006233',
    'container.build_time' => 1718009889,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM5qszJh');
