<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFPi7Y8Q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFPi7Y8Q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFPi7Y8Q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFPi7Y8Q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFPi7Y8Q\App_KernelDevDebugContainer([
    'container.build_hash' => 'FPi7Y8Q',
    'container.build_id' => '364a6f58',
    'container.build_time' => 1716906944,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFPi7Y8Q');
